"""empty message

Revision ID: 0a82ff6ac977
Revises: caaf14bea7db
Create Date: 2024-06-26 18:57:36.445957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a82ff6ac977'
down_revision: Union[str, None] = 'caaf14bea7db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kind',
    sa.Column('kindCd', sa.String(length=255), nullable=False),
    sa.Column('knm', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('kindCd')
    )
    op.create_index(op.f('ix_kind_kindCd'), 'kind', ['kindCd'], unique=False)
    op.create_index(op.f('ix_kind_knm'), 'kind', ['knm'], unique=False)
    op.create_table('sido',
    sa.Column('orgCd', sa.String(length=255), nullable=False),
    sa.Column('orgdownNm', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('orgCd')
    )
    op.create_index(op.f('ix_sido_orgCd'), 'sido', ['orgCd'], unique=False)
    op.create_index(op.f('ix_sido_orgdownNm'), 'sido', ['orgdownNm'], unique=False)
    op.create_table('sigungu',
    sa.Column('orgCd', sa.String(length=255), nullable=False),
    sa.Column('uprCd', sa.String(length=255), nullable=True),
    sa.Column('orgdownNm', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['uprCd'], ['sido.orgCd'], ),
    sa.PrimaryKeyConstraint('orgCd')
    )
    op.create_index(op.f('ix_sigungu_orgCd'), 'sigungu', ['orgCd'], unique=False)
    op.create_index(op.f('ix_sigungu_orgdownNm'), 'sigungu', ['orgdownNm'], unique=False)
    op.create_index(op.f('ix_sigungu_uprCd'), 'sigungu', ['uprCd'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sigungu_uprCd'), table_name='sigungu')
    op.drop_index(op.f('ix_sigungu_orgdownNm'), table_name='sigungu')
    op.drop_index(op.f('ix_sigungu_orgCd'), table_name='sigungu')
    op.drop_table('sigungu')
    op.drop_index(op.f('ix_sido_orgdownNm'), table_name='sido')
    op.drop_index(op.f('ix_sido_orgCd'), table_name='sido')
    op.drop_table('sido')
    op.drop_index(op.f('ix_kind_knm'), table_name='kind')
    op.drop_index(op.f('ix_kind_kindCd'), table_name='kind')
    op.drop_table('kind')
    # ### end Alembic commands ###
